default: &default
  adapter: <%= ENV['RSS_DB_DRIVER'] %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['RSS_DB_SCHEMA'] %>

test:
  <<: *default
  database: <%= ENV['RSS_DB_SCHEMA'] %>

production:
  <<: *default
  database: <%= ENV['RSS_DB_SCHEMA'] %>
  username: <%= ENV['RSS_DB_USER'] %>
  password: <%= ENV['RSS_DB_PASS'] %>
